### ISSUE TITLE
Can't connect to slave

### ISSUE THREAD

**Issue by MDrules02** [deevus/docker-plex-remote-transcoder#13]
Here is what I am using for Master

```
sudo docker run \
--name plex \
--network=host \
-e TZ=America/Indiana/Indianapolis \
-e ADVERTISE_IP="http://10.10.1.38:32400/" \
-e MASTER_IP="10.10.1.38" \
-e PLEX_UID="1002" \
-e PLEX_GID="1002" \
-e SLAVE_IP="10.10.1.20" \
-e SLAVE_PORT="2222" \
-e SLAVE_USER="plex" \
-v /mnt/plex/config:/config \
-v /mnt/plex/transcode:/transcode \
-v /mnt/tv/:/data/tvshows \
-v /mnt/movies/Movies:/data/movies \
deevus/plex-remote-transcoder:master-latest
```

Here is what I am using for Slave

```
sudo docker run \
--name plex-slave \
-p 2222:22 \
-e TZ=America/Indiana/Indianapolis \
-e MASTER_IP="10.10.1.38" \
-e PLEX_UID="1002" \
-e PLEX_GID="1002" \
-v /mnt/plex/config:/config \
-v /mnt/plex/transcode:/transcode \
-v /mnt/tv/:/data/tvshows \
-v /mnt/movies/Movies:/data/movies \
deevus/plex-remote-transcoder:slave-latest
```

Here is the master output I get:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 40-plex-first-run: executing...
Creating pref shell
Plex Media Server first run setup complete
[cont-init.d] 40-plex-first-run: exited 0.
[cont-init.d] 50-plex-update: executing...
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] 61-prt-master-install: executing...
Installing Plex Remote Transcoder
IP address of this machine: Renaming original transcoder
[cont-init.d] 61-prt-master-install: exited 0.
[cont-init.d] 62-prt-add-slaves: executing...
Host: Port: User: We're going to add the following transcode host:
  Host: 10.10.1.20
  Port: 2222
  User: plex
Proceed: [y/n]Host successfully added
[cont-init.d] 62-prt-add-slaves: exited 0.
[cont-init.d] 62-ssh-keygen: executing...
Generating public/private rsa key pair.
Your identification has been saved in /config/.ssh/id_rsa.
Your public key has been saved in /config/.ssh/id_rsa.pub.
The key fingerprint is:
SHA256:wBMFfm7qdBoLHMMFKUmGuF7XRi7XRl/TNWTftVPHnIU root@pet-minnow
The key's randomart image is:
+---[RSA 2048]----+
|.oo...oo.     oBX|
|o.o .+ o .   oEo@|
| . .  X + . . .oo|
|.  o + X o .    .|
|. . = + S        |
| . . o o         |
|    o + .        |
|     + =         |
|      +          |
+----[SHA256]-----+
[cont-init.d] 62-ssh-keygen: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Starting Plex Media Server.

```
Here is what I get on slave:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-ssh-init: executing...
INFO: importing public key
cat: /config/.ssh/id_rsa.pub: Permission denied
[cont-init.d] 10-ssh-init: exited 1.
[cont-init.d] 40-plex-first-run: executing...
chown: changing ownership of '/transcode/Transcode/Sessions': Operation not permitted
chown: changing ownership of '/transcode/Transcode': Operation not permitted
chown: changing ownership of '/transcode': Operation not permitted
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
Plex Media Server first run setup complete
[cont-init.d] 40-plex-first-run: exited 0.
[cont-init.d] 50-plex-update: executing...
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
Permission denied: /config/Library/Application Support/Plex Media Server/Preferences.xml
failed to load external entity "/config/Library/Application Support/Plex Media Server/Preferences.xml"
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] 60-prt-install: executing...
Installing Plex Remote Transcoder
IP address of this machine: Error loading config: [Errno 13] Permission denied: '/config/.prt.conf'
Renaming original transcoder
[cont-init.d] 60-prt-install: exited 0.
[cont-init.d] 61-prt-register: executing...
Host: Port: Traceback (most recent call last):
  File "/usr/local/bin/prt", line 9, in <module>
    load_entry_point('prt==0.4.4', 'console_scripts', 'prt')()
  File "/usr/local/lib/python2.7/dist-packages/prt-0.4.4-py2.7.egg/prt.py", line 680, in main
EOFError: EOF when reading a line
[cont-init.d] 61-prt-register: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

```

I went in and change file permission on config to add read for everyone.
Then my slave output looks like this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-ssh-init: executing...
INFO: importing public key
[cont-init.d] 10-ssh-init: exited 0.
[cont-init.d] 40-plex-first-run: executing...
chown: changing ownership of '/transcode/Transcode/Sessions': Operation not permitted
chown: changing ownership of '/transcode/Transcode': Operation not permitted
chown: changing ownership of '/transcode': Operation not permitted
Plex Media Server first run setup complete
[cont-init.d] 40-plex-first-run: exited 0.
[cont-init.d] 50-plex-update: executing...
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] 60-prt-install: executing...
Installing Plex Remote Transcoder
IP address of this machine: Error loading config: [Errno 13] Permission denied: '/config/.prt.conf'
Renaming original transcoder
[cont-init.d] 60-prt-install: exited 0.
[cont-init.d] 61-prt-register: executing...
Traceback (most recent call last):
  File "/usr/local/bin/prt", line 9, in <module>
    load_entry_point('prt==0.4.4', 'console_scripts', 'prt')()
  File "/usr/local/lib/python2.7/dist-packages/prt-0.4.4-py2.7.egg/prt.py", line 680, in main
Host: Port: EOFError: EOF when reading a line
[cont-init.d] 61-prt-register: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

I have /config set as NFS share with (rw,sync,no_subtree_check)

Is there something I'm missing?

**Comment by deevus** [comment]
Looks like there is still permission issues from the following lines in your output:

```
chown: changing ownership of '/transcode/Transcode/Sessions': Operation not permitted
chown: changing ownership of '/transcode/Transcode': Operation not permitted
chown: changing ownership of '/transcode': Operation not permitted
...
IP address of this machine: Error loading config: [Errno 13] Permission denied: '/config/.prt.conf'
```

So it seems like an issue with your mounted volumes

**Comment by MDrules02** [comment]
I changed the /transcode to local instead of trying to use NFS, I also changed the file permission on .prt.conf

My slave output now looks like this:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-ssh-init: executing...
INFO: importing public key
[cont-init.d] 10-ssh-init: exited 0.
[cont-init.d] 40-plex-first-run: executing...
Plex Media Server first run setup complete
[cont-init.d] 40-plex-first-run: exited 0.
[cont-init.d] 50-plex-update: executing...
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] 60-prt-install: executing...
Installing Plex Remote Transcoder
IP address of this machine: Renaming original transcoder
[cont-init.d] 60-prt-install: exited 0.
[cont-init.d] 61-prt-register: executing...
Traceback (most recent call last):
  File "/usr/local/bin/prt", line 9, in <module>
    load_entry_point('prt==0.4.4', 'console_scripts', 'prt')()
  File "/usr/local/lib/python2.7/dist-packages/prt-0.4.4-py2.7.egg/prt.py", line 680, in main
Host: Port: EOFError: EOF when reading a line
[cont-init.d] 61-prt-register: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
I double checked /config/.ssh/ and authorized_keys wasn't there.  I went ahead and dropped the id_rsa.pub in and now it is able to ssh in.

**Comment by MDrules02** [comment]
I think something is still wrong with the ssh.  Now I get the following:

ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
ssh: /usr/lib/plexmediaserver/libcrypto.so.1.0.0: no version information available (required by ssh)
process_mux_new_session: tcgetattr: Inappropriate ioctl for device
bash: line 0: cd: /transcode/Transcode/Sessions/plex-transcode-1825e50426473a48-com-plexapp-android-13a0de40-ba88-4e20-bcef-70aac0e02c71: No such file or directory

**Comment by deevus** [comment]
It's probably an incompatibility with a newer version of plex. I haven't updated this repo in a long while. 

If you're able to figure it out I'll happily take a PR
